# Generated by Django 4.2 on 2024-09-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='autor',
            new_name='author',
        ),
    ]
